# -*- python -*-

import os, fnmatch
Import('env')

def findFiles(pattern, subdir=''):
    files = []
    for file in os.listdir(os.path.join(Dir('.').srcnode().abspath, subdir)):
        if fnmatch.fnmatch(file, pattern):
            files.append(File(os.path.join(subdir, file), Dir('.')))
    return files

for n in (env.Install('$pkgdatadir/waves', 'README' ),
          env.Install('$pkgdatadir/waves', findFiles('*.la'))):
    env.Alias('install', n)
