'\" t
.\"     Title: answering_machine.conf
.\"    Author: Gernot Hillier <gernot@hillier.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 08/13/2013
.\"    Manual: CapiSuite 0.5.git
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "ANSWERING_MACHINE\&." "5" "08/13/2013" "[FIXME: source]" "CapiSuite 0.5.git"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
answering_machine.conf \- configuration of CapiSuite answering machine
.SH "DESCRIPTION"
.PP
This file holds all available config options for the answering machine provided by the default scripts distributed with
CapiSuite\&. It is read from
/etc/capisuite/answering_machine\&.conf
or
/usr/local/etc/capisuite/answering_machine\&.conf
(depending on the installation)\&.
.PP
It is divided into one or more sections\&. A section begins with the section name in square brackets like
[section]
while the options are
key="value"
lines\&.
.PP
A special section called
[GLOBAL]
and one section for each user called
[<username>]
are required\&.
\fIThe \fR\fI<username>\fR\fI must be a valid system user\fR\&.
.PP
The
[GLOBAL]\-section defines some global options like pathnames and default settings for options that can be overridden in the user\-sections\&. The user\-sections hold all the options which belong to a particular user\&.
.SH "THE [GLOBAL] SECTION"
.PP
\fBaudio_dir="/path/to/audiodir/"\fR
.RS 4
The answering machine script uses several wave files, for example a global announcement if the user hasn\*(Aqt set his own and some spoken word fragments for the remote inquiry and the menu presented there\&. These audio files are searched in this directory\&. If user_audio_files is enabled (see
\fBuser_audio_files\fR), each user can also provide his own audio snippets in his user_dir (see
\fBvoice_user_dir\fR)\&.
.sp
This option is mandatory\&.
.RE
.PP
\fBvoice_user_dir="/path/to/userdir/"\fR
.RS 4
This directory is used to save user specific data to\&. It must exist and the user
CapiSuite
runs as must have write permission to it\&. It will contain one subdirectory for each configured user (named like his userid)\&. The following subdirectories are used below the user\-specific dir:
.PP
user_dir/username/
.RS 4
Here the user may provide his own audio_files (see also option
\fBuser_audio_files\fR
below)\&. The user defined announcement is also saved here\&.
.RE
.PP
user_dir/username/received/
.RS 4
Received voice calls are saved here\&.
.RE
.sp
This option is mandatory\&.
.RE
.PP
\fBuser_audio_files="0"\fR
.RS 4
If set to
1, each user may provide his own audio files in his user directory (see
\fBvoice_user_dir\fR)\&. If set to
0, only the audio_dir (see
\fBvoice_audio_dir\fR) will be searched\&.
.sp
This option is optional\&. If not set, it defaults to not reading own user audio files (0)\&.
.RE
.PP
\fBvoice_delay="15"\fR
.RS 4
Sets the default value for the delay for accepting an incoming call in (in seconds)\&. A value of
10
means that the answering machine accepts incoming calls 10 seconds after the incoming connection request\&. This value can be overwritten in the user sections individually\&.
.sp
This option is mandatory\&.
.RE
.PP
\fBannouncement="announcement\&.la"\fR
.RS 4
Sets the default name to use for user announcements\&. The announcements are searched in
user_dir/username/announcement
then\&. If not found, a global announcement containing the called MSN will be played\&. This value can be overwritten in the user sections individually\&.
.sp
This option is optional\&. If not set, it defaults to "announcement\&.la"\&.
.RE
.PP
\fBrecord_length="60"\fR
.RS 4
Default setting for the maximum record length in seconds\&. This value can be overwritten in the user sections individually\&.
.sp
This option is optional\&. If not set, it defaults to 60 seconds\&.
.RE
.PP
\fBrecord_silence_timeout="5"\fR
.RS 4
Default setting for the record silence timeout in seconds\&. When set to a value greater than 0, the recording will be aborted if silence is detected for the given amount of seconds\&. Set this to 0 to disable it\&. This value can be overwritten in the user sections individually\&.
.sp
This option is optional\&. If not set, it defaults to 5 seconds\&.
.RE
.PP
\fBvoice_email_from="<mailaddress>"\fR
.RS 4
You can set a default originator ("From"\-address) for the e\-mails
CapiSuite
sends here\&.
.sp
This option is optional\&. If you set this to an empty string, the destinator is used as originator (i\&.e\&. if "gernot" receives a voice call, the mail comes from "gernot" to "gernot")\&.
.RE
.SH "THE USER SECTIONS"
.PP
\fBvoice_delay\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBannouncement\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBrecord_length\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBrecord_silence_timeout\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBvoice_email_from\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBvoice_numbers="<number1>,<number2>,\&.\&.\&."\fR
.RS 4
A list containing the numbers on which this user wants to receive incoming voice calls\&. These numbers are used to differ between users \- so the same number must not appear in more than one user section! The numbers are separated with commas and
\fIno blanks\fR
are allowed\&. The answering machine script does also automatic fax detection, so a fax can be sent to this number\&. When this list is set to
*,
\fIall\fR
incoming calls will be accepted for this user (use with care!)\&. This is only useful for a setup with only one user which wants to receive any call\&.
.sp
If for any reason
\fIno destination\fR
number is signalled for special MSNs (austrian telecom seems to do this for the main MSN, where it is called "Global Call"), you can use the special sign
\-
which means "no destination number available"\&.
.sp
This option is optional\&. If not set, the user won\*(Aqt receive voice calls\&.
.RE
.PP
\fBvoice_email=""\fR
.RS 4
If given, this string indicates email\-addresses where the received faxes and voice calls will be sent to\&. If it is empty, they will be sent to the user account on the system
CapiSuite
is running on\&. More addresses are separated by commas\&. If you don\*(Aqt want emails to be sent at all, use the action option (see
\fBvoice_action\fR)\&.
.sp
This option is optional\&. If not set, the calls are mailed to the system account\&.
.RE
.PP
\fBpin="<your PIN>"\fR
.RS 4
The answering machine also supports a remote inquiry function\&. This function is used by entering a PIN (Personal Identification Number) while the announcement is played\&. This PIN can be setup here\&. If you don\*(Aqt want to use the remote inquiry function, just use an empty PIN setting\&. The PIN doesn\*(Aqt have a maximal length \- but perhaps you should not use 200 digits or you perhaps won\*(Aqt be able to remember them (I won\*(Aqt at least)\&. ;\-)
.sp
This option is optional\&. If not set, remote inquiry is disabled\&.
.RE
.PP
\fBvoice_action="MailAndSave"\fR
.RS 4
Here you can define what action will be taken when a call is received\&. Currently, three possible actions are supported:
.PP
\fBMailAndSave\fR
.RS 4
The received call will be mailed to the given address (see
\fBvoice_email\fR
above) and saved to the
voice_user_dir
(see global options)
.RE
.PP
\fBSaveOnly\fR
.RS 4
The call will be only saved to the
voice_user_dir
(see global options)
.RE
.PP
\fBNone\fR
.RS 4
Only the announcement will be played \- no recording is done\&.
.RE
.sp
This option is mandatory\&.
.RE
.SH "SEE ALSO"
.PP
capisuite(8), capisuite\&.conf(5), fax\&.conf(5), capisuitefax(1)
.SH "AUTHOR"
.PP
\fBGernot Hillier\fR <\&gernot@hillier.de\&>
.RS 4
Author.
.RE
