'\" t
.\"     Title: capisuitefax
.\"    Author: Gernot Hillier <gernot@hillier.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 08/13/2013
.\"    Manual: CapiSuite 0.5.git
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CAPISUITEFAX" "1" "08/13/2013" "[FIXME: source]" "CapiSuite 0.5.git"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
capisuitefax \- sending faxes with the CapiSuite default scripts
.SH "SYNOPSIS"
.HP \w'\fBcapisuitefax\fR\ 'u
\fBcapisuitefax\fR [\-q] [\-n] [\-u\ \fIuser\fR] [\-A\ \fIadr\fR] [\-S\ \fIsubj\fR] \-d\ \fInumber\fR file...
.HP \w'\fBcapisuitefax\fR\ 'u
\fBcapisuitefax\fR [\-q] \-a\ \fIid\fR
.HP \w'\fBcapisuitefax\fR\ 'u
\fBcapisuitefax\fR \-h
.HP \w'\fBcapisuitefax\fR\ 'u
\fBcapisuitefax\fR \-l
.SH "DESCRIPTION"
.PP
The default scripts for
CapiSuite
come with the tool
\fBcapisuitefax\fR
for sending faxes\&.
.PP
It will be called with some parameters telling it which file to send (it currently only supports PostScript and PDF files) and to which number\&. It will then enqueue the job converted to the right format into the send queue from which it\*(Aqs collected by another
CapiSuite
script and sent to the destination\&. If the sending was completed successfully or failed finally after trying for some time, the according user will get an email telling him/her what has happened\&.
.SH "OPTIONS"
.PP
\fB\-a id\fR
.RS 4
Abort the job with the given id\&. To get a job id, use the
\fB\-l\fR
option\&.
.RE
.PP
\fB\-A adr\fR
.RS 4
The addressee of the fax\&. This option is (currently) only for informational purposes and will be quoted in the sent status mail\&.
.RE
.PP
\fB\-d number\fR
.RS 4
The number which should be called (destination of the fax)
.RE
.PP
\fB\-h\fR
.RS 4
Show a short commandline help
.RE
.PP
\fB\-l\fR
.RS 4
Shows the jobs which are currently in the send queue\&.
.RE
.PP
\fB\-n\fR
.RS 4
Don\*(Aqt use the configured dial prefix for this job\&. Useful for internal jobs\&.
.RE
.PP
\fB\-q\fR
.RS 4
Be quiet, don\*(Aqt output informational messages
.RE
.PP
\fB\-S subj\fR
.RS 4
A subject for the fax\&. This option is (currently) only for informational purposes and will be quoted in the sent status mail\&.
.RE
.PP
\fB\-u user\fR
.RS 4
Send fax as another user\&. Only allowed if
\fBcapisuitefax\fR
is called as user
root\&. This is mainly helpful for realizing extensions to e\&.g\&. do network faxing\&.
.RE
.PP
\fBfile\&.\&.\&.\fR
.RS 4
One or more PostScript/PDF files to send to this destination\&. More than one PostScript file will produce several separate fax jobs\&.
.RE
.SH "SEE ALSO"
.PP
capisuite(8), capisuite\&.conf(5), fax\&.conf(5), answering_machine\&.conf(5)
.SH "AUTHOR"
.PP
\fBGernot Hillier\fR <\&gernot@hillier.de\&>
.RS 4
Author.
.RE
