'\" t
.\"     Title: capisuite.conf
.\"    Author: Gernot Hillier <gernot@hillier.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 08/13/2013
.\"    Manual: CapiSuite 0.5.git
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "CAPISUITE\&.CONF" "5" "08/13/2013" "[FIXME: source]" "CapiSuite 0.5.git"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
capisuite.conf \- configuration of the CapiSuite daemon
.SH "DESCRIPTION"
.PP
The options for the
CapiSuite
daemon are configured here\&. They will be presented in brief here \- for further details please refer to the comments in the configuration file itself\&.
.SH "OPTIONS"
.PP
\fBincoming_script="/path/to/incoming\&.py"\fR
.RS 4
This option tells
CapiSuite
which script should be executed at incoming calls\&. Only change this if you want to use your own script\&.
.RE
.PP
\fBidle_script="/path/to/idle\&.py"\fR
.RS 4
This option reflects the path and name of the idle script\&. This script is called in regular intervalls to check if any outgoing call should be done\&. As above, the default should be ok if you don\*(Aqt use your own script\&.
.RE
.PP
\fBidle_script_interval="30"\fR
.RS 4
Here you can define how often the idle script should be executed\&. The number given is the interval between subsequent invocations in seconds\&. Lesser numbers give you quicker response to queued jobs but also a higher system load\&. The default should be ok in most cases\&.
.RE
.PP
\fBlog_file="/path/to/capisuite\&.log"\fR
.RS 4
This file will be used for all "normal" messages printed by
CapiSuite
telling you what it does\&. Error messages are written to a special log (see below)\&.
.RE
.PP
\fBlog_level="1"\fR
.RS 4
You can define how detailled the log output of
CapiSuite
will be\&. The default will give you some informational messages for each incoming and outgoing call and should be enough for normal use\&. I would recommend to only increase it if you encounter some problems\&. Logs of higher level are mainly intended for developers, so just use them if you want to report a problem or have some know\-how of the CAPI interface and the internals of
CapiSuite\&.
.RE
.PP
\fBlog_error="/path/to/capisuite\&.error"\fR
.RS 4
All errors which
CapiSuite
detects internally and in your scripts will end up here\&. They are written to an extra file so that they don\*(Aqt get lost in the normal log\&. Please check this log regularly for any messages \- especially when you encounter problems\&. Please report all messages you don\*(Aqt understand and which aren\*(Aqt caused by your own script\-modifications to the
CapiSuite
team\&.
.RE
.PP
\fBDDI_length="0"\fR
.RS 4
When your ISDN card is connected to an ISDN interface in PtP mode, i\&.e\&. if you use DDI which, in understandable words mean you have only one ISDN phone number and can define your own extensions as you like, you have to set the length of your extension numbers here\&. In Germany, PtP mode is called "Anlagenanschluss"\&. Let\*(Aqs say you use 1234\-000 till 1234\-999, then your DDI_length would be 3\&. If you set this to 0, DDI/PtP is disabled\&.
.sp
If you\*(Aqre not sure what all this should mean, then chances are high you don\*(Aqt use DDI and can leave this option as it is\&.
.RE
.PP
\fBDDI_base_length="0"\fR
.RS 4
This option is only used when DDI_length is not 0\&. This is the length of your base number \- in the example above it would be 4\&.
.RE
.PP
\fBDDI_stop_numbers=""\fR
.RS 4
If you usually use extension numbers of a specified length, but also want to use some shorter ones (e\&.g\&. the "\-0" extension for you switchboard), then you can list these shorter extensions here, separated by commas\&.
.RE
.SH "SEE ALSO"
.PP
capisuite(8), fax\&.conf(5), answering_machine\&.conf(5), capisuitefax(1)
.SH "AUTHOR"
.PP
\fBGernot Hillier\fR <\&gernot@hillier.de\&>
.RS 4
Author.
.RE
