'\" t
.\"     Title: fax.conf
.\"    Author: Gernot Hillier <gernot@hillier.de>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 08/13/2013
.\"    Manual: CapiSuite 0.5.git
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "FAX\&.CONF" "5" "08/13/2013" "[FIXME: source]" "CapiSuite 0.5.git"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fax.conf \- configuration of the CapiSuite fax services
.SH "DESCRIPTION"
.PP
This file holds all available config options for the fax services provided by the default scripts distributed with
CapiSuite\&. It is read from
/etc/capisuite/fax\&.conf
or
/usr/local/etc/capisuite/fax\&.conf
(depending on the installation)\&.
.PP
It is divided into one or more sections\&. A section begins with the section name in square brackets like
[section]
while the options are
key="value"
lines\&.
.PP
A special section called
[GLOBAL]
and one section for each user called
[<username>]
are required\&.
\fIThe \fR\fI<username>\fR\fI must be a valid system user\fR\&.
.PP
The
[GLOBAL]\-section defines some global options like pathnames and default settings for options that can be overridden in the user\-sections\&. The user\-sections hold all the options which belong to a particular user\&.
.SH "THE [GLOBAL] SECTION"
.PP
\fBspool_dir="/path/to/spooldir/"\fR
.RS 4
This directory is used to archive sent (or failed) jobs\&. It must exist and the user
CapiSuite
runs as must have write permission to its subdirectories\&. Two subdirectories are used:
.PP
spooldir/done/
.RS 4
Jobs finished successfully are moved to this directory\&.
.RE
.PP
spooldir/failed/
.RS 4
Job which have failed finally end up here\&.
.RE
.sp
This option is mandatory\&.
.RE
.PP
\fBfax_user_dir="/path/to/userdir/"\fR
.RS 4
This directory is used to store fax jobs and received documents to\&. It must exist and the user
CapiSuite
runs as must have write permission to it\&. It will contain one subdirectory for each configured user (named like his userid)\&. The following subdirectories are used below the user\-specific dir:
.PP
user_dir/username/received/
.RS 4
Received faxes are saved here\&.
.RE
.PP
user_dir/username/sendq/
.RS 4
Fax files to be sent are queued here by
\fBcapisuitefax\fR\&.
.RE
.sp
This option is mandatory\&.
.RE
.PP
\fBsend_tries="10"\fR
.RS 4
When a fax can\*(Aqt be sent to the destination for any reason, it\*(Aqs tried for several times\&. This setting limits the number of tries\&. If all tries failed, the job will be moved to the failed dir (see
\fBfax_spool_dir\fR) and the user will get a mail\&.
.sp
This option is optional\&. If not given, it defaults to 10 tries\&.
.RE
.PP
\fBsend_delays="60,60,60,300,300,3600,3600,18000,36000"\fR
.RS 4
When a fax can\*(Aqt be sent to the destination for any reason, it\*(Aqs tried again\&. This setting specifies the delays in seconds between subsequent tries\&. The different values are separated with commas and
\fIno blanks\fR\&. The list should have send_tries\-1 (see
\fBfax_send_tries\fR) values \- if not, surplus entries are ignored and missing entries are filled up with the last value\&. The default should just be ok giving you increasing delays for up to 10 tries\&.
.sp
This option is optional\&. If not given, it defaults to the list shown above\&.
.RE
.PP
\fBsend_controller="1"\fR
.RS 4
If you have more than one ISDN controller installed (some active cards for more than one basic rate interface like the AVM C2 or C4 are also represented as multiple controllers for CAPI applications like
CapiSuite), you can decide which controller (and therefore which basic rate interface) should be used for sending your faxes\&. All controllers are numbered starting with 1\&. If you\*(Aqre not sure which controller has which number, increase the log level to at least 2 in
CapiSuite
(see
the section called \(lqConfiguration of CapiSuite\(rq), restart it and have a look in the log file where all controllers will be listed then\&. Unfortunately,
CapiSuite
isn\*(Aqt able to use more than one controller for sending faxes at the moment, so no list is allowed here\&. If you have only one controller, just leave it at
1
.sp
This option is optional\&. If not given, it defaults controller 1\&.
.RE
.PP
\fBoutgoing_MSN="<your MSN>"\fR
.RS 4
This number is used as our own number for outgoing calls\&. If it\*(Aqs not given, the first number of fax_numbers is used (see user sections)\&. If this one is also empty, the user can\*(Aqt send faxes\&. Please replace with one valid MSN of your ISDN interface or leave empty\&. This value can be overwritten in the user sections individually\&.
.sp
This option is optional\&. If not given, it defaults to empty\&.
.RE
.PP
\fBoutgoing_timeout="60"\fR
.RS 4
Default setting which defines how many seconds we will wait for a successful connection after dialing the number\&. This value can be overwritten in the user sections individually\&.
.sp
This option is optional\&. If not given, it defaults to 60 seconds\&.
.RE
.PP
\fBdial_prefix=""\fR
.RS 4
If anything is entered here, it will be used as a prefix which is added to any number given to
\fBcapisuitefax\fR
as prefix\&. This is e\&.g\&. very helpful if your ISDN adapter is connected to a PBX which needs "0" for external calls\&. It\*(Aqs also possible to disable its usage later for a certain fax document, so setting this will certainly not prevent you from placing internal calls without prefix\&.
.sp
This option is optional\&. If not given, it defaults to an empty prefix\&.
.RE
.PP
\fBfax_stationID="<your faxID>"\fR
.RS 4
Default fax station ID to use when sending a fax document\&. The station ID is usually the number of your fax station in international format, so an example would be "+49 89 123456" for a number in Munich, Germany\&. Station IDs may only consist of the "+"\-sign, spaces and the digits 0\-9\&. The maximal length is 20\&. This value can be overwritten in the user sections individually\&.
.sp
This option is mandatory\&.
.RE
.PP
\fBfax_headline="<your faxheadline>"\fR
.RS 4
Default fax headline to use when sending a fax document\&. Where and if this headline will be presented depends on the implementation of your CAPI driver\&. The headline should have a reasonable length to fit on the top of a page, but there\*(Aqs no definite limit given\&.
.sp
This option is optional\&. If not given, it defaults to an empty headline\&.
.RE
.PP
\fBfax_email_from="<mailaddress>"\fR
.RS 4
You can set a default originator ("From"\-address) for the e\-mails
CapiSuite
sends here\&.
.sp
This option is optional\&. If you set this to an empty string, the destinator is used as originator (i\&.e\&. if "gernot" receives a fax, the mail comes from "gernot" to "gernot")\&.
.RE
.SH "THE USER SECTIONS"
.PP
\fBoutgoing_MSN\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBoutgoing_timeout\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBfax_stationID\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBfax_headline\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBfax_email_from\fR
.RS 4
User specific value for the corresponding global option
.RE
.PP
\fBfax_numbers="<number1>,<number2>,\&.\&.\&."\fR
.RS 4
A list containing the numbers on which this user wants to receive incoming fax calls\&. These numbers are used to differ between users \- so the same number must not appear in more than one user section! The numbers are separated with commas and
\fIno blanks\fR
are allowed\&. The first number of the list also serves as our own number for sending a fax if outgoing_MSN is not set (see
\fBoutgoing_MSN\fR)\&.
.sp
If you want to use the same number for receiving fax and voice calls, please
\fIdo not\fR
enter it here\&. Use the voice_numbers option instead (see
answering_machine\&.conf(5)) \- the answering machine has a built in fax detection and can also receive faxes\&.
.sp
When this list is set to
*,
\fIall\fR
incoming calls will be accepted for this user (use with care!)\&. This is only useful for a setup with only one user which wants to receive any call as fax\&.
.sp
If for any reason
\fIno destination\fR
number is signalled for special MSNs (austrian telecom seems to do this for the main MSN, where it is called "Global Call"), you can use the special sign
\-
which means "no destination number available"\&.
.sp
This option is optional\&. If not given, the user can\*(Aqt receive fax documents\&.
.RE
.PP
\fBfax_email=""\fR
.RS 4
If given, this string indicates email\-addresses where the received faxes will be sent to\&. More addresses are separated by commas\&. If it is empty, they will be sent to the user account on the system
CapiSuite
is running on\&. The address is also used to send status reports for sent fax jobs to\&. If you don\*(Aqt want emails to be sent at all, use the action option (see option
\fBfax_action\fR) below\&.
.sp
This option is optional\&. If not given, the mail is sent to the system account\&.
.RE
.PP
\fBfax_action="MailAndSave"\fR
.RS 4
Here you can define what action will be taken when a call is received\&. Currently, two possible actions are supported:
.PP
\fBMailAndSave\fR
.RS 4
The received call will be mailed to the given address (see
\fBfax_email\fR
above) and saved to the
\fBfax_user_dir\fR
(see global options)
.RE
.PP
\fBSaveOnly\fR
.RS 4
The call will be only saved to the fax_user_dir (see global options)
.RE
.sp
This option is mandatory\&.
.RE
.SH "SEE ALSO"
.PP
capisuite(8), capisuite\&.conf(5), answering_machine\&.conf(5), capisuitefax(1)
.SH "AUTHOR"
.PP
\fBGernot Hillier\fR <\&gernot@hillier.de\&>
.RS 4
Author.
.RE
