# -*- python -*-

Import('env')
env.Append(capisuite_sources = Dir('.'))

SConscript('capisuite-py/SConscript')
libmodule = SConscript('modules/SConscript')
libappl   = SConscript('application/SConscript')
libback   = SConscript('backend/SConscript')

env.ExtraDist(Split("""
    capisuite-py/SConscript
    modules/SConscript
    application/SConscript
    backend/SConscript
    """))

capisuite = env.Program('capisuite',
                        ['main.cpp', libappl, libmodule, libback])
#env.AddPostAction(capisuite, 'strip $TARGET')

capisuite_conf = env.FileSubst('capisuite.conf', 'capisuite.conf.in')

# -- install --
env.Alias('install-exec', env.Install('$sbindir', capisuite))
env.Alias('install',      env.Install('$pkgsysconfdir', capisuite_conf))
